### ISSUE TITLE
"no matching package named `skia` found" after cargo build

### ISSUE THREAD

**Issue by vyp** [servo/rust-layers#217]
1. `git clone https://github.com/servo/rust-layers && cd rust-layers`
2. `cargo build`

Produces following error code output:

```
    Updating registry `https://github.com/rust-lang/crates.io-index`
    Updating git repository `https://github.com/servo/skia`
    Updating git repository `https://github.com/servo/rust-azure`
    Updating git repository `https://github.com/servo/rust-glx`
    Updating git repository `https://github.com/servo/io-surface-rs`
    Updating git repository `https://github.com/servo/rust-egl`
no matching package named `skia` found (required by `layers`)
location searched: https://github.com/servo/skia
version required: *
```

I am new to rust so it's also likely I'm doing something wrong, but not sure what because the location https://github.com/servo/skia does exist. Do you get the same error?

**Comment by Manishearth** [comment]
cc @SimonSapin 

looks like we've broken older builds with the cratesification?

**Comment by vyp** [comment]
@Manishearth you've confirmed you can reproduce right? Because it might save some time otherwise. ;)

**Comment by Manishearth** [comment]
I haven't tried. But there was a major change that was made which could have easily broken things.

**Comment by Manishearth** [comment]
The issue is that https://github.com/servo/skia/blob/master/Cargo.toml is called servo-skia now.

`cargo update -p skia --precise 0391f0dcf9a6b1c01d701326b0564e82d8350bc5` will fix it temporarily

**Comment by SimonSapin** [comment]
Oops, I need to finish dealing with all this, sorry.

Yeah, I renamed the crate because https://crates.io/crates/skia is already taken. Existing builds with a `Cargo.lock` file (like Servo commits, e.g. if bisecting) should be fine, but indeed even after everything lands renaming like that breaks building earlier commits of e.g. rust-layers without a lock file. I suppose that’s an inherent limitation of git dependencies: there’s nothing like Semantic Versioning for commit hashes.

**Comment by Manishearth** [comment]
We can just create a second git repo and leave the original one so that bisecting and all works

**Comment by SimonSapin** [comment]
Ugh. Also, do we care about bisecting rust-layers without Servo?

**Comment by vyp** [comment]
Maybe, have you tried contacting the author of that crate in case he can rename (if crates *can* be renamed/transferred that is), because it seems as though it's been a placeholder for nearly a year now. cc @DiamondLovesYou (author)

**Comment by vyp** [comment]
Although I guess that is the point of placeholders anyway, so dismiss that as you see appropriate.

**Comment by SimonSapin** [comment]
Crates can not be renamed. But you can add/remove owners, publish the same content under a different name, and a publish different content under the previous name with newer version number.

I’ve contacted the owner of https://crates.io/crates/skia, they do have plans for it. It might be good to converge eventually and co-maintain it, but for now let’s stick with servo-skia.

**Comment by metajack** [comment]
I hate this global namespace crap.

Someone needs to go squat all our crate names.

**Comment by SimonSapin** [comment]
```sh
$ for crate in $(git grep -B2 \"git+ components/servo/Cargo.lock|grep name|cut -d\" -f2); wget https://crates.io/api/v1/crates/$crate -q -O /dev/null || echo $crate >> /tmp/crates/names
$ cat /tmp/crates/names 
azure
brotli
clipboard
energymon
energymon-default-sys
energymon-sys
freetype
gaol
hbs-common-sys
hbs-pow
hbs-pow-sys
ipc-channel
layers
mozjs_sys
offscreen_gl_context
stb_image
xml5ever
$ for name in $(cat /tmp/crates/names); (cargo new /tmp/crates/$name && cd /tmp/crates/$name && sed -i '/dependencies/d' Cargo.toml && echo -e 'description = "Squatting"\nlicense = "CC0-1.0"'>>Cargo.toml && cargo publish && cargo owner -a github:servo:cargo-publish)
…

**Comment by metajack** [comment]
xml5ever, stb_image, mozjs_sys, offscreen_gl_context, layers, ipc-channel, gaol, freetype, clipboard, azure should all be squatted by us. I'm not sure if brotli is ours or what hbs-* and energeymon-* are.

**Comment by SimonSapin** [comment]
To clarify, all the names above are crates that Servo uses through git dependencies and were not on crates.io. I just published an empty crate on crates.io for each of them, and added github:servo:cargo-publish as an owner.

If any of them turns out to be maintained by someone else, I’m happy to give away ownership as appropriate.

While I’m at it, here are the git dependencies that have the same name as something that was already on crates.io before this. I haven’t checked which are the same crates:

```
angle
bincode
clock_ticks
core-text
egl
expat-sys
fontconfig
fontconfig-sys
freetype-sys
glutin
glx
io-surface
js
simd
skia
tenacious
webdriver

**Comment by Manishearth** [comment]
tenacious is my package, Servo just has a fork which gets used sometimes.

**Comment by jdm** [comment]
Webdriver, core-text, expat-sys are the same.

**Comment by SimonSapin** [comment]
I’m in the middle of moving use to using expat-sys from crates.io as part of https://github.com/servo/skia/issues/70. For others, is there a reason to keep using git dependencies for things that are also on crates.io?

**Comment by Manishearth** [comment]
For glutin we keep a fork which actually differs from the original.

**Comment by vyp** [comment]
Thanks everyone!
